apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-coupon-db
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      mservice: coupon
      type: db
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        mservice: coupon
        type: db
    spec:
      containers:
      - name: coupon-db
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-coupon-db
  labels:
    app: redis
    mservice: coupon
    type: db
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    mservice: coupon
    type: db