apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  selector:
    matchLabels:
      app: go-api
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: go-api
        tier: backend
        track: stable
    spec:
      containers:
      - name: go-api
        image: pavlechko/go-container:0.7
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis-coupon-db
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: go-api
spec:
  selector:
    app: go-api
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080